@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZWE4YWJjZGEwNWYwOThhMWFjOTg1OCIsImlhdCI6MTY3NTUyMzI0OCwiZXhwIjoxNjc1NTM3NjQ4fQ.OCCSsn54tiIzY2Rhmu6RKbQ8DtnZzLC3ZaC-it9jDEg

// USER
###
POST http://localhost:5000/user/register HTTP/1.1
content-type: application/json

{
	"name": "manu11",
    "email": "manuaa@test.com",
    "password": "ciaociao",
    "birthDate": "09/09/01",
    "phoneNumber": "342423423",
    "preference": "Cani"
}
###
POST http://localhost:5000/user/login HTTP/1.1
content-type: application/json

{
    "email": "manuel@test.com",
    "password": "ciaociao"
} 

// ANIMALS
###
GET http://localhost:5000/animals/list HTTP/1.1
Authorization: Bearer {{token}}
###
GET http://localhost:5000/animals/63d03fa3788d002cb12754af HTTP/1.1
Authorization: Bearer {{token}}
###
DELETE http://localhost:5000/animals/63d06ecd969c1886977ede6e HTTP/1.1
Authorization: Bearer {{token}}
###
POST http://localhost:5000/animals/ HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
    "weight" : "0-10kg",
    "gender" : "Male",
    "birthdate" : "06/06/2001",
    "breed" : "Dalmata",
    "species" : "Cane",
    "imageURI" : "https://upload.wikimedia.org/wikipedia/commons/4/4f/Dalmatian_puppy%2C_four_months.png",
    "name" : "Pinuzzo"
}


// PRODUCTS
###
GET http://localhost:5000/products/list HTTP/1.1
###
GET http://localhost:5000/products/cibo/list HTTP/1.1
###
GET http://localhost:5000/products/63d03a2174724ca39b25122b HTTP/1.1


// SCORES
###
GET http://localhost:5000/scores/list HTTP/1.1
###
POST http://localhost:5000/scores/ HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "punteggio": 2000,
    "game": "quiz"
}

// SEDI
###
GET http://localhost:5000/sedi/list HTTP/1.1


/// THREADS
###
GET http://localhost:5000/threads/list HTTP/1.1
###
POST http://localhost:5000/threads HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "title": "Nuovo Thread"
}

###
POST http://localhost:5000/threads/63de2a9bcf4d16be3e23a416/newMessage HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "content": "Altro Nuovo Messaggio"
}